### ISSUE TITLE
BUG: Waffle link in README is broken

### ISSUE THREAD

**Issue by combinatorist** [codefordenver/habitat-group-contacts#79]
I was really curious, but I still don't know what "waffle" is. :(

**Comment by jberns** [comment]
@combinatorist So waffle was a kanban board kind of like Trello but they no longer exist.  If you want to update it can remove the couple references/links to it from the README and submit another pull request.

FYI if you are interested in this project in general let me know, we are thinking of doing a phase 2 in the near future.
